name: Build, scan & publish image
on:
  push:
    tags:
      - latest
      - v*
  pull_request:
    branches: [ "**" ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: quickview,cves
          image: ${{ steps.meta.outputs.tags }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Dockerhub Registry
        if: ${{ github.event_name == 'push' }}
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ladamalina/gatling
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag_names: true

      - name: Publish to Github Registry
        if: ${{ github.event_name == 'push' }}
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ladamalina/gatling
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tag_names: true
