name: Build & publish image to Github registry
on:
  push:
    tags:
      - latest
      - v*

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ladamalina/gatling
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tag_names: true
