name: Build & push image to Dockerhub
on:
  push:
    tags:
      - latest
      - v*

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Dockerhub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ladamalina/gatling
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag_names: true
